#####################################
###  TOMCAT SERVER CONFIGURATION ####
#####################################
server:
  port: 8081
  servlet:
    context-path: /api
#####################################
##  Resource Server Configuration ###
#####################################
spring:
  security:
    oauth2:
      resource-server:
        id: RestHouseCustomerApi
        check-token-url: ${OAUTH_CHECK_TOKEN_URL}
      client:
        id: ${OAUTH_CLIENT_ID}
        secret: ${OAUTH_CLIENT_SECRET}